### ISSUE TITLE
Project Won't Build

### ISSUE THREAD

**Issue by skl131313** [baseball435/TerraLegion#14]
Having a hard time building the project, using Android Studio 2.1.2. I can't comply with the instructions to create the build configuration. When I got to select a module for the Run->Edit Config step, the only module that appears is the "TerraLegion" one. Only have some basic knowledge of Android Studio, maybe someone else will have better luck figuring it out. If you could try to set it up from a clean install in a virtual machine, I find it helps.

![pic](https://cloud.githubusercontent.com/assets/8701667/16567703/74739fa0-41ef-11e6-98eb-77e232774411.png)

**Comment by jmrapp1** [comment]
Interesting. Just clarifying, when you opened the project, did you select the build.gradle file that is in the top directory of the project?

**Comment by skl131313** [comment]
Yes I did. It looks like it ran some scripts and downloaded some files before it opened. Also tried other things like selecting the folder and such but it didn't change anything.

**Comment by jmrapp1** [comment]
Can you go to the project explorer on the left side of Android Studio which lays out the folder hierarchy and post a screenshot if it extended out? I want to see where it is starting.

**Comment by skl131313** [comment]
Not sure what happened but after I reinstalled Android Studio again it seems to be working now. Sorry for the trouble.
