### ISSUE TITLE
Placing block in rabbit

### ISSUE THREAD

**Issue by AppPhil** [baseball435/TerraLegion#2]
You can place a block on the position of a rabbit. Then the rabbit stucks there but doesn't die.

**Comment by baseball435** [comment]
I have added this issue to the list and will leave the issue open until fixed. Nice catch.

**Comment by jmrapp1** [comment]
Yes this is an issue. It may be a good idea when placing a block to check for entities within the radius of the player reach. For each entity, if the place that the block wants to be placed collides with the entity position, don't place the block. Take a look at [this method](https://github.com/jmrapp1/TerraLegion/blob/master/core/src/com/jmrapp/terralegion/game/world/chunk/Chunk.java#L163) to find entities within a given radius.
