### ISSUE TITLE
Unable to build android target.  android:dexDebug task fails

### ISSUE THREAD

**Issue by dsyang** [baseball435/TerraLegion#23]
The task fails with com.android.dex.DexException: Multiple dex files define Lorg/hamcrest/Description

This comes up when I click the run button in Android Studio as well as when I use gradlew from the command line:

```
> ./gradlew android:installDebug
...
:android:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lorg/hamcrest/Description;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)
```

My setup:
Android Studio 2.2 Preview 1Build #AI-145.2878421, built on May 17, 2016
JRE: 1.8.0_40-b25 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Gradle version 2.2

**Comment by dsyang** [comment]
From the internet, it looks like this has something to do with the fact that junit 4.10 includes a copy of hamcrest 1.1[[1](http://saltnlight5.blogspot.com/2012/10/whats-up-with-junit-and-hamcrest.html)]

**Comment by jmrapp1** [comment]
This happens randomly, what you'll need to do is enable the multidex option and delete the _generated_ folder. To do this, go to the build.gradle file for the Android project and add the following lines within the _android_ block:

```
defaultConfig {
     multiDexEnabled true
}
```

After this, go to the project explorer on the left, go to the android project, go to the _build_ folder, and delete the entire _generated_ folder. Then clean and rebuild and it should work.

**Comment by dsyang** [comment]
Thanks for the tip @jmrapp1 and the very detailed explanation! This ended up not being the issue though, I fixed it by excluding hamcrest-core from json-simple as described here: http://stackoverflow.com/questions/32543197/error-json-simple-java-util-zip-zipexception-duplicate-entry-org-hamcrest-bas

It now runs on my android!
