### ISSUE TITLE
Can't pass trees

### ISSUE THREAD

**Issue by AppPhil** [baseball435/TerraLegion#3]
When you go and on your left / right there is a tree it will stop you like a normal block. I would like it if you could go on also if there's a tree because I don't like it that I have to remove every tree to walk through the world.

**Comment by jmrapp1** [comment]
Currently this is how the game is designed to work. It's not an issue, but more of a personal opinion on how it should function. I would like for players to pass through the trees as well, but as of right now, unless someone modifies the code to allow passable and destroyable blocks, it will remain how it is.
