### ISSUE TITLE
Sprites taken from other games

### ISSUE THREAD

**Issue by ghost** [baseball435/TerraLegion#34]
"Stolen" sprites should be replaced with original and/or open-source sprites (similar to [minetest/minetest_game](https://github.com/minetest/minetest_game)). Personally, I do not have a problem with them, but Mojang and Re-Logic might feel differently. The sooner the sprites can be replaced, the better.

**Comment by jordanb84** [comment]
Since they're placeholders anyway, I'm sure something can be found on OpenGameArt. http://opengameart.org/content/voxel-pack looks like a good start, for example.

( On a side note, I'll get into this project more once I'm done with something else! :) )

**Comment by jmrapp1** [comment]
Yes, new images are really needed I just have yet to find a graphic designer willing to make a few images for it! 

Edit: @jordanb84 just changed the images in #35 and they look great!
