### ISSUE TITLE
Wrong splitting of items in inventory

### ISSUE THREAD

**Issue by AppPhil** [baseball435/TerraLegion#4]
When you got a odd number of items and you click on the button to halve them you loose one item.
As an example: You got 3 blocks. You click on the halve button and then you got only 2 blocks but in different slots. I know that you can't really halve odd numbers but I think it would be better when you could as an example halve 3 to 2 and 1.

**Comment by jmrapp1** [comment]
Yes that is how it should function how you suggest. Thank you for the submission.

**Comment by AppPhil** [comment]
I think I fixed it. Pull Request: https://github.com/baseball435/Terraria-Clone/pull/6

**Comment by jmrapp1** [comment]
Great job!
