### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [baseball435/TerraLegion#47]
It would be neat to have this game on F-Droid :)

**Comment by jordanb84** [comment]
While that would be nice, it's not in a releasable state yet. I plan to keep working at it until it is, though.

(On that note, we either need a vector artist for the current style or an easier art style for us programmers to add onto. It's hard to add much without art.)

**Comment by jmrapp1** [comment]
I agree, I believe that this will be something that can be done in the future. Because of this I am going to close this request, but keep it in mind for the future.
