### ISSUE TITLE
Can't place torch on players position

### ISSUE THREAD

**Issue by AppPhil** [baseball435/TerraLegion#5]
I don't know if this is planned but I think you should be able to place torches where you're standing.

**Comment by jmrapp1** [comment]
You're right, you should be able to! This will stay open until fixed.

**Comment by AppPhil** [comment]
Would you prefer adding an attribute like "can be placed on players position" to Block or just checkig if the placed block is a torch?

**Comment by jmrapp1** [comment]
Crap, I completely forgot, there is a variable in the constructor of the _Block_ class called "collides". If this is set to false entities wont collide with it. Set that to false for the wooden log and then what needs to be done is when setting a block, check if the block trying to be set collides with entities. If it does, don't let them place it on themselves. If it doesn't, let them place it on themselves.

To set it to false, go to the _BlockManager_ class and find where a block is initialized with the _BlockType.WOOD_ type as the identifier.

**Comment by AppPhil** [comment]
But the game doesn't check if the block would collide with the player. It checks if the collisionTestRect collides with the player here: https://github.com/baseball435/TerraLegion/blob/master/core/src/com/jmr/terraria/game/views/ui/GameHud.java#L159

**Comment by AppPhil** [comment]
Please take the second one.
