### ISSUE TITLE
Items Are Not Saved And Loaded

### ISSUE THREAD

**Issue by jmrapp1** [baseball435/TerraLegion#7]
The items that the player currently has are not saved and loaded. This should be something that should be saved and loaded within the [WorldIO class](https://github.com/baseball435/Terraria-Clone/blob/master/core/src/com/jmr/terraria/game/world/World.java).

**Comment by AppPhil** [comment]
Here's how I would do: https://github.com/baseball435/Terraria-Clone/pull/11
