### ISSUE TITLE
Crafting doesn't check for required items

### ISSUE THREAD

**Issue by jmrapp1** [baseball435/TerraLegion#9]
When selecting an item to craft from the crafting screen, it does not check if the player has the required items and just gives the player the item.

**Comment by AppPhil** [comment]
What do you think about the implementation of it?
Should there be one class for one crafting recipe?

**Comment by jmrapp1** [comment]
You'll want to take a look at the [crafting package](https://github.com/baseball435/TerraLegion/tree/master/core/src/com/jmr/terraria/game/item/crafting) which already contains the framework setup for the crafting recipes. There are currently two crafting recipes and you can craft them in-game by going to your inventory and then pressing the crafting icon at the top to go to the crafting screen.

**Comment by jordanb84** [comment]
If I'm understanding the code correctly after a glance at the `CraftingRecipe` and `Inventory` classes, shouldn't the implementation be a simple call to an `inventory.hasItems()`function in an if statement surrounding the current item removal loop in the `craft()` function?

The `hasItems()` function could be added in the `Inventory` class as a loop through each passed item, checking them against the `hasItem()` function.

**Comment by jmrapp1** [comment]
The [CraftingRecipe](https://github.com/jmrapp1/TerraLegion/blob/master/core/src/com/jmrapp/terralegion/game/item/crafting/CraftingRecipe.java) has a method called `canCraft()`, but it just hasn't been implemented. I do like the idea for the `hasItem()` method. It could take an item and an amount as parameters or an itemstack as a parameter as well.
